name: Test

on:
  push:
    branches: 'master'
  pull_request:

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Set up Rust
      uses: actions-rs/toolchain@v1.0.6
    - name: Set up the environment
      run: python x.py setup
    - name: Build with cargo
      run: python x.py build --all --verbose
    - name: Run cargo tests
      run: python x.py test --all --verbose
    - name: Npm install
      run: npm ci
      working-directory: vscode-epcs-hover
    - name: Npm compile
      run: npm run compile
      working-directory: vscode-epcs-hover
